### ISSUE TITLE
is_utf8_start removed from Base

### ISSUE THREAD

**Issue by hayd** [tanmaykm/MutableStrings.jl#3]
See https://github.com/JuliaLang/julia/pull/12655

Easy to add back within the Module:

```
is_utf8_start(byte::UInt8) = ((byte&0xc0)!=0x80)
```

**Comment by tanmaykm** [comment]
Thanks @hayd . Will check it out.

**Comment by tanmaykm** [comment]
I've not been using this package recently. Strings have undergone quite some changes and it will be more than trivial to get this working properly in 0.4.

I'll deprecate this package, unless someone else needs this.

**Comment by hayd** [comment]
Maybe cc @ScottPJones @quinnj.

**Comment by ScottPJones** [comment]
Hi, I was in the process of trying to fix MutableStrings, just didn't have time yet to wrap that up, and yes, the code looked like it needed a lot of reworking because of all the changes to strings in 0.4.
@tanmaykm, I think having mutable strings in Julia would be great, I'm very glad you made this package, but I'd agree that it should be deprecated, in favor of moving forward on something like @quinnj's https://github.com/quinnj/Strings.jl (which combined with some of the ideas from @StefanKarpinski's bytevec's and the ideas being bounced around about having Arrays based on Buffers, could help make Julia have a world class string implementation, IMO).

**Comment by tanmaykm** [comment]
Thanks @ScottPJones , I have now deprecated MutableStrings.

Closed with  https://github.com/JuliaLang/METADATA.jl/commit/ef3c5db231c9f5c894022619f39eff9dc979125a and https://github.com/tanmaykm/MutableStrings.jl/commit/706df63868c57be34ca949b17e57ef8c2a18acf0
